#!/bin/bash

# Function to add and commit a file with the provided commit message
function add_and_commit {
  file="$1"
  commit_message="$2"

  git add "$file"
  git commit -m "$commit_message"
}

# List of files and corresponding commit messages
declare -a files=(
  "0x01_shell_permissions/1-who_am_i|Add who_am_i script"
  "0x01_shell_permissions/10-mirror_permissions|Add mirror_permissions script"
  "0x01_shell_permissions/2-groups|Add groups script"
  "0x01_shell_permissions/3-new_owner|Add new_owner script"
  "0x01_shell_permissions/4-empty|Add empty script"
  "0x01_shell_permissions/5-execute|Add execute script"
  "0x01_shell_permissions/6-multiple_permissions|Add multiple_permissions script"
  "0x01_shell_permissions/7-everybody|Add everybody script"
  "0x01_shell_permissions/8-James_bond|Add James_bond script"
  "0x01_shell_permissions/9-John_Doe|Add John_Doe script"
  "0x01_shell_permissions/hello|Add hello script"
  "0x01_shell_permissions/olleh|Add olleh script"
)

# Loop through the list of files and commit them one by one
for entry in "${files[@]}"
do
  file="${entry%%|*}"
  commit_message="${entry#*|}"

  add_and_commit "$file" "$commit_message"
done

# Push changes to the remote repository
git push origin <branch-name>
